### ISSUE TITLE
V0.1.0 Release

### ISSUE THREAD

**Issue by thebioengineer** [phuse-org/valtools#33]
I want to track what we need to do for an initial release here. I think we have a lot of really cool features going on, but not all features we have listed in the issues here need to be complete for a minimal, functional, package that someone could use

As I see it, these are the features we need for a v0.1.0, and which branch addresses it if I can identify it:
- [x] ability to create a package with validation infrastructure (`vt_create_package`)
- [x] ability to add validation infrastructure to already started package (`vt_use_validation_config`,`vt_use_validation`)
- [x] complete description file for package [branch: (update_description [#25])]
- [x] ability to create entries from templates [branch: (config_integration[#34] )]
    - [x] req (`vt_use_req`)
    - [x] test case (`vt_use_test_case`)
    - [x] test code (`vt_use_test_code`)
- [x] custom roxygen tags: editor and editDate
- [x] parse roxygen tags to get [branch: (scrape_authors[#43] )]
    - [x] req authors
    - [x] function authors
    - [x] test case authors
    - [x] test code authors
- [x] Create validation report skeleton [branch: (scharp_legacy)]
    - [x] create from template (#45)
    - [x] generate tables for signatures of validation participants  [branch: ( eli/sig_table[#58]), issue: (#39)]
    - [x] capture validation environment (#40)
    - [x] generate table of authorships (#41)
        - [x] reqs
        - [x] functions
        - [x] test cases
        - [x] test code
    - [x] report req-test_code coverage table 
    - [x] report all reqs
    - [x] report all test cases
    - [x] report results of test cases [branch: ( test_code_eval [#47])]
    - [x] NEWS details
- [x] valtools methods to 
    - [x] execute validation report on demand (`vt_validate_source()`)
    - [x] execute validation on build/release (`vt_validate_build()`/ `vt_validate_install()`) [branch: (function_roxy_copy [#48]) - copy function roxy into inst/validation/R]
    - [x] execute validation report on installed packages (`vt_validate_installed_package`)
    - [x] execute validation report in a separate location as source

Tier v0.1.1 items include
- [x] complete dynamic referencing in R
- [x] complete dynamic referencing via LUA filters [branch: (pandoc-dynamic-ref [#27])]

**Comment by elimillera** [comment]
@thebioengineer @mariev 
It looks like we're getting pretty close on initial release. Is the templating for the validation rmd itself in the works yet? I can get started on that if it isn't.

**Comment by mariev** [comment]
@elimillera yes - validation report helper functions are already part of #3 and #15 but were waiting on all the changes introduced by config and other details. 

We still haven't finalized tags for dynamic referencing - see discussion in #27.

**Comment by thebioengineer** [comment]
hey @elimillera - as far as I am aware, the template is not in progress. however, there are the functions that go to populate the template that are still in the works/needing to be written. 

What might be good, and correct me if i'm wrong @mariev, would be to look at the functions in the `scharp_legacy` branch and start working on those. These are the "guts" of the validation report and we need to update these and get them on the same level (error messages, etc) first I think

**Comment by thebioengineer** [comment]
hey @elimillera, I have a branch `parse_roxygen_generics` that might impact a lot of the legacy code as well. will be opening a PR soon on that. 

For PR's for these helper functions, lets make them specific and narrow as possible. I think that will facilitate narrower code review and faster iteration.

**Comment by elimillera** [comment]
@mariev @thebioengineer 

I've added #39, #40, and #41 to add in. I'll have PRs in for those in soon!

**Comment by thebioengineer** [comment]
We are so close to intial release (V0.1.0) - all core functionality is there. last to dos:

 - [ ] PR #128 smooths out the final "must have" functionality as defined here
 - [ ] PR #63 is a vignette to explain how to use {valtools} in its current state
 - [ ] PR #103 is a small update to add the project creator to rstudio easily
